export const candidateContent = {
  candidateJonathan: {
    name: "Jonathan Barlow",
    ballotStatus: "ballot",
    bio: 'Jonathan Barlow grew up all over Detroit and graduated from Renaissance High School. He’s the founder of entertainment business The WKND Co. and Let’s Talk Roundtable. This is Barlow’s second time running for public office; he also ran for Detroit City Council in 2009.{newParagraph}Barlow is <a href="https://www.votebarlow.com/platform/">running on a platform</a> of starting a $500 million fund for businesses in the city, creating jobs and building affordable housing.',
    age: "40",
    neighborhood: "Southwest Detroit",
    website: "https://www.votebarlow.com/platform/",
    instagram: "https://www.instagram.com/votebarlow/",
    email: "mailto:info@votebarlow.com",
    quote1:
      "Electricity affordability | Barlow said, as mayor, he would explore publicly owned renewable energy initiatives to reduce the cost of electricity. “By investing in community-owned renewable energy, Detroit can create long-term resilience, energy independence and affordability,” he stated in response to Outlier Media’s candidate questionnaire.",
    quote2:
      "Water affordability | Barlow said the city should never shut off residents’ water, no matter what it costs taxpayers.{newParagraph}“Water is a basic human right, not a privilege tied to income,” he wrote. “My administration would prioritize structural solutions — such as income-based water rates, green infrastructure and public ownership models — to ensure long-term affordability and dignity for all Detroiters.”",
    quote3:
      "Transit | As mayor, Barlow wants to increase the frequency of all bus routes. “Frequency is the core driver of trust and usability in public transit,” he wrote. “Reliable, frequent transit is essential to equitable access to jobs, health care and education — especially Detroiters without a vehicle.”",
    spotifyId: "5RKQ5NdjSh2QzD4MaunT91",
    songTitle: "“Don’t Stop Believin’” by Journey.",
    quizResponse1: "2",
    quizResponse2: "3",
    quizResponse3: "1",
    quizResponse4: "2",
    quizResponse5: "2",
    quizResponse6: "3",
    quizResponse7: "3",
    quizResponse8: "2",
    quizResponse9: "1",
    quizResponse11: "2",
    quizResponse12: "3",
    quizResponse13: "1",
    quizResponse14: "4",
    quizResponse15: "4",
    quizResponse16: "3",
    quizResponse17: "3",
    quizResponse18: "1",
    quizResponse19: "2",
    quizResponse20: "3",
    quizResponse21: "3",
  },
  candidateRogelio: {
    name: "Rogelio Landin",
    bio: 'Rogelio Landin is running as a write-in candidate for mayor. The Southwest Detroit native graduated from Cass Technical High School and now lives downtown.{newParagraph}He’s a longtime activist and businessman who in recent years has served on five neighborhood advisory councils — which are responsible for negotiating with developers on major projects. He’s also on the newly formed Tenants’ Rights Commission.{newParagraph}Landin is <a href="https://landinformayor.com/vision">running on a platform</a> of annexing 28 “distressed” communities surrounding Detroit, giving the mayor greater control over the city’s public school district, and building a World Trade Center in Detroit.',
    ballotStatus: "writein",
    website: "https://landinformayor.com/",
    email: "mailto:landinformayor@gmail.com",
    age: "71",
    neighborhood: "Downtown",
    quote1:
      "Community benefits ordinance | Landin says the community benefits ordinance does not need any changes.{newParagraph}“As the most experienced person in the city having been elected and appointed to five NACs and supporting two others, I have been involved in over $12 billion in development projects downtown and the Gordie Howe (International Bridge),” he wrote. “It’s working as it was designed to and voted for by the citizens of Detroit.”",
    quote2:
      "Immigration | Landin believes the city should limit cooperation with federal immigration authorities.{newParagraph}“My response is confined to our current situation,” he wrote for Outlier Media’s candidate questionnaire. “This is a complex matrix of variables, and there is no one answer applicable to every case. In the case of our current environment, we are undermining our own laws, specifically those as relate to due process as provided for in the 5th and 14th amendments.”",
    quote3:
      "Electricity affordability | Landin wants to explore publicly owned renewable energy initiatives to reduce the cost of electricity.{newParagraph}“The city could contribute to the entire scope of promoting innovation in alternative energy and sustainability, while creating a competitive environment for existing providers. This would impact education, workforce training, entrepreneurship, and make the city a very real partner in our new innovation economy.”",
    spotifyId: "0WfMlP2YNlbQZBxtyYVJO5",
    songTitle: "“Welcome 2 Detroit” by Trick Trick, featuring Eminem.",
    quizResponse1: "1",
    quizResponse2: "2",
    quizResponse3: "1",
    quizResponse4: "1",
    quizResponse5: "1",
    quizResponse6: "2",
    quizResponse7: "3",
    quizResponse8: "1",
    quizResponse9: "2",
    quizResponse11: "2",
    quizResponse12: "1",
    quizResponse13: "1",
    quizResponse14: "3",
    quizResponse15: "3",
    quizResponse16: "3",
    quizResponse17: "4",
    quizResponse18: "3",
    quizResponse19: "3",
    quizResponse20: "4",
    quizResponse21: "3",
  },
  candidateSaunteel: {
    name: "Saunteel Jenkins",
    bio: 'Saunteel Jenkins grew up on Detroit’s westside and graduated from Cass Technical High School. She now lives on the eastside.{newParagraph}She served as chief of staff for former City Council President Maryann Mahaffey and later became council president herself. She resigned during her second term, as the city was emerging from bankruptcy, to become CEO of The Heat and Warmth Fund, where she worked for 10 years.{newParagraph}Jenkins is <a href="https://www.saunteeljenkins.com/saunteel-six">running on a platform</a> of a master plan for each of the city’s seven districts and providing resources for jobs, apprenticeships and businesses.',
    ballotStatus: "ballot",
    website: "https://www.saunteeljenkins.com/",
    email: "mailto:info@saunteeljenkins.com",
    age: "54",
    neighborhood: "Elmwood Park",
    quote1:
      "Violence intervention | Jenkins believes sanctioned community groups, supported with government funding, are the best way to handle violence in the community.{newParagraph}“Because prevention is the most effective crime reduction strategy. You need safe spaces for kids, positive educational enrichment opportunities and career pathways for hope,” Jenkins wrote in response to Outlier Media’s candidate questionnaire. “Policing is part of the solution, but by the time police respond, it is reactive. We need to prevent violence in the first place.”",
    quote2:
      "Immigration | Jenkins thinks the city should not dedicate resources to immigration enforcement, but should cooperate with federal officials who have a valid warrant.{newParagraph}“Detroit should be a welcoming city, and we should work with nonprofits to ensure immigrants know their rights (in the correct language) and have resources if or when confronted by immigration officials,” she wrote.",
    quote3:
      "Affordable housing | “More affordable housing is essential, but as cost of living rises, we have to consider rent control,” Jenkins wrote. “More affordable housing is a long-term solution, but rent control is doable in the near term.”",
    youtubeId: "gcZf2CLxbgA",
    songTitle:
      "Detroit Academy of Arts and Sciences Choir’s rendition of “Empire State of Mind” by Jay-Z.",
    quizResponse1: "2",
    quizResponse2: "2",
    quizResponse3: "2",
    quizResponse4: "3",
    quizResponse5: "2",
    quizResponse6: "3",
    quizResponse7: "3",
    quizResponse8: "2",
    quizResponse9: "3",
    quizResponse11: "2",
    quizResponse12: "3",
    quizResponse13: "3",
    quizResponse14: "2",
    quizResponse15: "4",
    quizResponse16: "2",
    quizResponse17: "3",
    quizResponse18: "2",
    quizResponse19: "2",
    quizResponse20: "3",
    quizResponse21: "3",
  },
  candidateTodd: {
    name: "Todd Perkins",
    bio: 'Todd Perkins grew up on the eastside and still lives there. He graduated from University of Detroit Jesuit High School. Perkins is a lawyer and plans to step down from the law firm he runs if he’s elected mayor.{newParagraph}Perkins is <a href="https://perkinsforthepeople.com/vision/">running on a platform</a> of fiscal responsibility and accountability.',
    ballotStatus: "ballot",
    website: "https://perkinsforthepeople.com/",
    email: "mailto:info@perkinsforthepeople.com",
    age: "55",
    neighborhood: "North End",
    quote1:
      "Immigration | Perkins said the city should not dedicate resources to immigration enforcement, but should cooperate with federal officials when there is a valid warrant for a specific individual.{newParagraph}As mayor, he said he would “ensure Detroit Police and city agencies prioritize local safety over federal immigration priorities, protect immigrant families from unlawful targeting or profiling and work with community organizations to support access to services, housing and legal protection.”",
    quote2:
      "Water affordability | “As mayor, I will prioritize expanding Detroit’s water affordability program with a stable city-funded reserve and partnerships with philanthropic organizations, working with state and federal partners to unlock grant funding and modernizing billing systems to provide better transparency,” Perkins wrote in response to Outlier Media’s candidate questionnaire.",
    quote3:
      "Transit | “Improving frequency and reliability across all bus routes is the most immediate way to restore trust in the city’s transit system and ensure Detroiters can access work, school, health care and daily needs without delay or hardship,” Perkins wrote.",
    spotifyId: "3qvuhGBr6BSdGPQsdf2gLr",
    songTitle: "“Living for the City” by Stevie Wonder.",
    quizResponse1: "1",
    quizResponse2: "2",
    quizResponse3: "2",
    quizResponse4: "3",
    quizResponse5: "2",
    quizResponse6: "1",
    quizResponse7: "2",
    quizResponse8: "2",
    quizResponse9: "3",
    quizResponse11: "2",
    quizResponse12: "2",
    quizResponse13: "4",
    quizResponse14: "3",
    quizResponse15: "4",
    quizResponse16: "3",
    quizResponse17: "3",
    quizResponse18: "1",
    quizResponse19: "2",
    quizResponse20: "2",
    quizResponse21: "3",
  },
  candidateJoel: {
    name: "Joel Haashiim",
    bio: 'Joel Haashiim is an entrepreneur and wholesaler who graduated from Thomas M. Cooley High School. He grew up on the city’s eastside.{newParagraph}Haashiim is <a href="https://joelhformayor.com/issues.html">running on a platform</a> of ordering a forensic audit of city finances and budget, creating a “true” policy for community benefits agreements and restoring citizens’ district councils.',
    ballotStatus: "ballot",
    website: "https://joelhformayor.com/",
    email: "mailto:info@joelhformayor.com",
    age: "75",
    neighborhood: "Northwest Detroit",
    quote1:
      "Property speculation | Haashiim said he would push for tax changes such as the land value tax to disincentivize speculation.{newParagraph}“Give purchasers a land use agreement with time frames ... to develop the property purchase. If the land is not developed within the time frame, then the city will foreclose on the property,” he wrote in response to Outlier Media’s candidate questionnaire.",
    quote2:
      "Electricity affordability | Haashiim wants to explore publicly owned renewable energy initiatives to reduce the cost of electricity. “Detroit must expand its lighting department and use alternative sources of power, such as a solar tax credit, to compete with DTE,” Haashiim wrote.",
    quote3:
      "Water affordability | “Having water is a right, not an option!” Haashiim wrote. “Residents should only pay for sewage.”",
    spotifyId: "687YZan9Gol1UVvbpUSO6Y",
    songTitle: "“I Wish” by Stevie Wonder.",
    quizResponse1: "1",
    quizResponse2: "3",
    quizResponse3: "3",
    quizResponse4: "3",
    quizResponse5: "2",
    quizResponse6: "3",
    quizResponse7: "4",
    quizResponse8: "2",
    quizResponse9: "1",
    quizResponse11: "2",
    quizResponse12: "1",
    quizResponse13: "1",
    quizResponse14: "3",
    quizResponse15: "5",
    quizResponse16: "3",
    quizResponse17: "1",
    quizResponse18: "4",
    quizResponse19: "2",
    quizResponse20: "1",
    quizResponse21: "3",
  },
  candidateMary: {
    name: "Mary Sheffield",
    bio: 'Mary Sheffield is the Detroit City Council president, representing District 5. She grew up on the westside and graduated from Southfield-Lathrup High School.{newParagraph}Sheffield is <a href="https://www.marysheffield.com/vision">running on a platform</a> of addressing root causes of crime, restoring neighborhoods through development and homeownership, and creating more opportunities for jobs and entrepreneurship.',
    ballotStatus: "ballot",
    website: "https://www.marysheffield.com/background",
    instagram: "https://www.instagram.com/marysheffield/",
    email: "mailto:mary@marysheffield.com",
    age: "37",
    neighborhood: "Lafayette Park",
    quote1:
      "Traffic safety | “Low-income Detroiters face high insurance; more penalties will worsen poverty,” Sheffield wrote in response to Outlier Media’s candidate questionnaire. “I’ll assess driver’s education access to understand if cost is a barrier, launch a speeding awareness campaign and add signage and monitors to problem areas.{newParagraph}“We need speed bumps and redesigned streets due to dangerous layouts. I’ll support targeted speed patrols only with community and DPD agreement on stop procedures.”",
    quote2:
      "Neighborhood improvement | “I will prioritize neighborhood development by targeting legacy institutions with technical and funding assistance,” Sheffield wrote.{newParagraph}“Motor City Match expansion and an Office of Small Business Development will support our entrepreneurs. By focusing on anchored development and empowering small businesses, we’ll achieve strong neighborhood revitalization, ending the ‘tale of two cities.’”",
    quote3:
      "Community benefits ordinance | “CBA enforcement is lacking. Developers rarely comply, and tracking is poor,” Sheffield wrote.{newParagraph}“My administration will create a dedicated Mayor’s Office capacity to track compliance. We won’t prioritize development ‘at all costs.’ Developers will understand that incentives must balance with realistic, trackable community benefits developed with neighborhoods, avoiding overpromising.”",
    youtubeId: "f9kiXtK2-vw",
    songTitle: "“Hello Detroit” by Sammy Davis Jr.",
    quizResponse1: "1",
    quizResponse2: "2",
    quizResponse3: "2",
    quizResponse4: "2",
    quizResponse5: "2",
    quizResponse6: "1",
    quizResponse7: "3",
    quizResponse8: "2",
    quizResponse9: "1",
    quizResponse11: "3",
    quizResponse12: "2",
    quizResponse13: "3",
    quizResponse14: "3",
    quizResponse15: "2",
    quizResponse16: "1",
    quizResponse17: "3",
    quizResponse18: "2",
    quizResponse19: "2",
    quizResponse20: "3",
    quizResponse21: "3",
  },
  candidateDanetta: {
    name: "DaNetta Simpson",
    bio: "DaNetta Simpson grew up on the eastside and graduated from Kettering High School. She’s a retired cosmetologist. This is her third time running for mayor.{newParagraph}Simpson is running on a platform of neighborhood development and stricter gun laws.",
    ballotStatus: "ballot",
    email: "mailto:danettasimpson1552@gmail.com",
    age: "53",
    neighborhood: "Eastside",
    quote1:
      "Violence intervention | In response to Outlier Media’s candidate questionnaire, Simpson said police should be most responsible for violence intervention, “because community groups will conspire with community criminals and commit crimes just to receive funds.”",
    quote2:
      "Safety | “No-guns signs should be posted at bars, schools, parks and more public places. It’s the law, but it’s mandatory to post it, because some people can’t own guns and the law still protects them, and everyone doesn’t know it’s the law and can’t read,” Simpson wrote.",
    quote3:
      "Right to renew | Simpson supports a requirement for landlords to offer lease renewals, with some protections for landlords. “Some tenants do not deserve right to renew,” Simpson said.",
    youtubeId: "f9kiXtK2-vw",
    songTitle: "“Hello Detroit” by Sammy Davis Jr.",
    quizResponse1: "1",
    quizResponse2: "2",
    quizResponse3: "3",
    quizResponse4: "4",
    quizResponse5: "3",
    quizResponse6: "3",
    quizResponse7: "2",
    quizResponse8: "2",
    quizResponse9: "3",
    quizResponse11: "1",
    quizResponse12: "2",
    quizResponse13: "5",
    quizResponse14: "3",
    quizResponse15: "4",
    quizResponse16: "2",
    quizResponse17: "3",
    quizResponse18: "1",
    quizResponse19: "2",
    quizResponse20: "1",
    quizResponse21: "5",
  },
  candidateSolomon: {
    name: "Solomon Kinloch",
    bio: 'Solomon Kinloch is the pastor of Triumph Church. He intends to step down from day-to-day operations if elected mayor, but said he would continue to preach on Sundays. He grew up on Detroit’s westside and graduated from Northwestern High School.{newParagraph}Kinloch is <a href="https://www.kinlochformayor.com/">running on a platform</a> of creating workforce training and new jobs, helping open 10 new grocery stores and building 10,000 affordable housing units.',
    ballotStatus: "ballot",
    website: "https://www.kinlochformayor.com/",
    instagram: "https://www.instagram.com/kinloch4mayor/",
    email: "mailto:info@kinlochformayor.com",
    age: "51",
    neighborhood: "Downtown",
    quote1:
      "Safety | “For too long, politicians have treated poverty as something to manage instead of something we solve,” Kinloch wrote in response to Outlier Media’s candidate questionnaire.{newParagraph}“Full employment and increased opportunity for everyone, is the best way to reduce crime. A Kinloch administration would prioritize training for unemployed residents, with dedicated outreach in high-unemployment ZIP codes.”",
    quote2:
      "Affordable housing | “I will convene philanthropy, business, labor and community partnerships to set up a housing strike force to build 10,000 affordable housing units,” Kinloch wrote. “We will build the largest down-payment assistance program in city history and provide low-interest loans to help teachers, police officers, first responders and working families live in Detroit.”",
    quote3:
      "Sidewalk repair | “We have to make Detroit walkable,” Kinloch wrote. “Last year, Detroit was named one of the most dangerous cities in the country for pedestrians.{newParagraph}“My administration will identify hotspots for pedestrian accidents and fatalities and improve the walking infrastructure in those areas, things like expanding sidewalks and increasing the frequency of crosswalks. We will also prioritize sidewalks used the most.”",
    spotifyId: "62aEe7mLn8wdWr0o26shwx",
    songTitle: "Aretha Franklin’s live rendition of “Amazing Grace.”",
    quizResponse1: "2",
    quizResponse2: "2",
    quizResponse3: "2",
    quizResponse4: "2",
    quizResponse5: "3",
    quizResponse6: "1",
    quizResponse7: "3",
    quizResponse8: "2",
    quizResponse9: "3",
    quizResponse11: "3",
    quizResponse12: "2",
    quizResponse13: "4",
    quizResponse14: "3",
    quizResponse15: "4",
    quizResponse16: "4",
    quizResponse17: "3",
    quizResponse18: "1",
    quizResponse19: "3",
    quizResponse20: "2",
    quizResponse21: "4",
  },
  candidateJames: {
    name: "James Craig",
    bio: 'James Craig is a former Detroit deputy mayor and police chief. He grew up on the westside and graduated from Cass Technical High School.{newParagraph}He’s <a href="https://www.chiefcraigformayor.com/vision">running on a platform</a> of expanding community policing efforts, revitalizing neighborhoods and cutting red tape for businesses.',
    ballotStatus: "ballot",
    website: "https://www.chiefcraigformayor.com/",
    facebook: "https://www.facebook.com/@james.craig.18",
    email: "mailto:info@chiefcraigformayor.com",
    age: "68",
    neighborhood: "Marina District",
    quote1:
      "Violence intervention | “Violence intervention isn't the responsibility of just one group. But if I had to choose who should be most responsible, I’d say it starts at home with family and then a broader partnership, with community and police,” Craig wrote in response to Outlier Media’s candidate questionnaire.{newParagraph}“Families and neighbors are also on the front lines. When communities are strong, when people care and watch out for one another, crime drops.”",
    quote2:
      "Immigration | Craig said the city should not dedicate resources to immigration enforcement but should cooperate with federal officials when there is a valid warrant for a specific individual.{newParagraph}“Detroit should remain a welcoming city to legal immigrants who contribute to our community,” he wrote. “At the same time, I support working with federal authorities to address illegal immigrants who commit violent crimes. Public safety must come first, while treating all people with dignity and fairness.”",
    quote3:
      "Community benefits ordinance | “It’s a valuable tool for ensuring that large-scale developments contribute positively to our neighborhoods. I support its goal of fostering community engagement and delivering tangible benefits,” Craig wrote.{newParagraph}“However, to maintain Detroit’s appeal to developers and ensure projects proceed smoothly, we must strike a balance that supports both community interests and economic growth.”",
    spotifyId: "4N0TP4Rmj6QQezWV88ARNJ",
    songTitle: "“Superstition” by Stevie Wonder.",
    quizResponse1: "3",
    quizResponse2: "2",
    quizResponse3: "2",
    quizResponse4: "4",
    quizResponse5: "2",
    quizResponse6: "3",
    quizResponse7: "2",
    quizResponse8: "1",
    quizResponse9: "1",
    quizResponse11: "3",
    quizResponse12: "3",
    quizResponse13: "1",
    quizResponse14: "3",
    quizResponse15: "2",
    quizResponse16: "1",
    quizResponse17: "3",
    quizResponse18: "3",
    quizResponse19: "1",
    quizResponse20: "3",
    quizResponse21: "2",
  },
  candidateArnold: {
    name: "Arnold Boyd",
    bio: 'Arnold Boyd is running as a write-in candidate for mayor. He grew up in Southwest Detroit and graduated from River Rouge High School, and he founded the Student Transportation Services Co.{newParagraph}Boyd is <a href="https://www.arnoldboyd.com/initiatives">running on a platform</a> of repairing relationships between community and police, creating affordable housing and supporting small businesses.',
    ballotStatus: "writein",
    website: "https://www.arnoldboyd.com/",
    instagram: "https://www.instagram.com/thearnoldboyd/",
    email: "mailto:campaign@arnoldboyd.com",
    age: "45",
    neighborhood: "Westside",
    quote1:
      "Immigration | “Detroit should focus on building trust with all residents,” Boyd wrote in response to Outlier Media’s candidate questionnaire. “We shouldn't use city resources for immigration enforcement but will cooperate when a valid warrant exists. This balances public safety with protecting immigrant communities from fear and discrimination.”",
    quote2:
      "Detroit Land Bank Authority | “The Land Bank needs a complete overhaul. It’s too difficult for residents to access properties, and too many sit vacant for too long,” Boyd stated. “We must create a system that puts Detroiters first — making ownership affordable, transparent, and focused on stabilizing neighborhoods.”",
    quote3:
      "Water affordability | Boyd said the city should devote more of its money to helping people pay for water if they can’t afford it; however, he said it should not ban shut-offs.{newParagraph}“Water is a basic human right. The city must invest more in helping residents afford their bills while balancing fiscal responsibility. Shut-offs should be the last resort, with strong assistance programs ensuring no family goes without water due to poverty,” he said.",
    spotifyId: "2w5fsswM1MlJu5rV44Qsf1",
    songTitle: "“Lose Yourself” by Eminem.",
    quizResponse1: "2",
    quizResponse2: "2",
    quizResponse3: "2",
    quizResponse4: "3",
    quizResponse5: "2",
    quizResponse6: "1",
    quizResponse7: "3",
    quizResponse8: "2",
    quizResponse9: "1",
    quizResponse11: "2",
    quizResponse12: "2",
    quizResponse13: "1",
    quizResponse14: "2",
    quizResponse15: "4",
    quizResponse16: "1",
    quizResponse17: "3",
    quizResponse18: "1",
    quizResponse19: "2",
    quizResponse20: "3",
    quizResponse21: "3",
  },
  candidateFred: {
    name: "Fred Durhal III",
    bio: "Fred Durhal grew up on the city’s eastside and westside, and graduated from the Detroit School of Arts. He is a former state legislator and current city councilmember for District 7.{newParagraph}Durhal is running on a platform of property tax reform, job creation and housing affordability.",
    ballotStatus: "ballot",
    website: "https://durhalfordetroit.com/",
    instagram: "https://www.instagram.com/durhaldelivers/",
    facebook: "https://www.facebook.com/durhaldelivers",
    email: "mailto:fdurhalcampaign@gmail.com",
    age: "41",
    neighborhood: "Westside",
    quote1:
      "Community benefits ordinance | Durhal said the community benefits ordinance (CBO) is too onerous for developers.{newParagraph}“Detroit’s CBO helps bring resources to neighborhoods as new developments rise,” he stated in response to Outlier Media’s candidate questionnaire. “To make it work, we must balance the needs of residents and developers, ensuring the ordinance delivers real benefits while keeping Detroit attractive to private investment and driving our city’s resurgence forward.”",
    quote2:
      "Property speculation | “Speculators and negligent landowners are holding Detroit back. As mayor, I’ll deliver comprehensive tax reform — raising taxes on blight and lowering them for families and small businesses,” Durhal wrote. “My plan will unlock vacant land for safe, walkable neighborhoods with thriving main streets, all while balancing the budget and improving quality of life citywide.”",
    quote3:
      "Overassessments | “Although making direct payments or reimbursements to overassessed residents is unconstitutional, I will create a Detroit Property Tax Relief Fund to develop a trust that would allow for reimbursement and/or tax rebates in some form,” Durhal wrote.{newParagraph}“Reimbursement will take legislative action in Lansing which my administration will make a priority to ensure residents who were overassessed are made whole.”",
    spotifyId: "3LwwCSGgp8QkLsSgmx5iRf",
    songTitle: "“Ain’t No Mountain High Enough” as sung by Diana Ross.",
    quizResponse1: "2",
    quizResponse2: "2",
    quizResponse3: "2",
    quizResponse4: "3",
    quizResponse5: "2",
    quizResponse6: "3",
    quizResponse7: "2",
    quizResponse8: "3",
    quizResponse9: "1",
    quizResponse11: "3",
    quizResponse12: "1",
    quizResponse13: "3",
    quizResponse14: "3",
    quizResponse15: "4",
    quizResponse16: "3",
    quizResponse17: "4",
    quizResponse18: "2",
    quizResponse19: "3",
    quizResponse20: "2",
    quizResponse21: "3",
  },
};
